'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Iq0Ghm5ltTi
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { loadStripe } from "@stripe/stripe-js";
import { Dialog, DialogTrigger, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

function PurchaseCoins({
  price_id,
  price, 
  coins,
  image,
  email
}) {
  const handleSubmit = async () => {
    const stripe = await loadStripe(process.env.NEXT_PUBLIC_STRIPE_PUBLIC_KEY);
    if (!stripe) {
      return;
    }

    try {
      const response = await fetch("/api/checkout_sessions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ price_id, coins, email }),
      });

      const data = await response.json();
      console.log(data);
      if (!data.ok) {
        throw new Error("Failed to create checkout session");
      }

      const result = await stripe.redirectToCheckout({
        sessionId: data.result.id,
      });

      
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <Card className="flex flex-col items-center p-4 space-y-2">
      <img src={image} alt="Coins" className="mb-4" />
      <div className="text-lg text-center font-semibold">{coins} Coins</div>
      <Badge variant="secondary">€{price}</Badge>
      <Button onClick={handleSubmit} variant="default" size="sm" className="mt-4">
        Purchase
      </Button>
    </Card>
  );
}

export function TopUpModal({ email }) {
  return (
    (<Dialog>
      <DialogTrigger asChild>
        <Button variant="default" size="sm">Buy Coins</Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[800px]">
        <DialogHeader>
          <DialogTitle>Purchase Coins</DialogTitle>
          <DialogDescription>Select a coin package to purchase.</DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 grid-cols-2 lg:grid-cols-3">
          <PurchaseCoins
            price_id="price_1PfJ2xP8KW8pdlk1qNH4Hjbo"
            price="5.99"
            coins="300"
            image="/coins_1.png"
            email={email}
          />
          <PurchaseCoins
            price_id="price_1PfJ3gP8KW8pdlk1p4960aQA"
            price="11.99"
            coins="650"
            image="/coins_2.png"
            email={email}
          />
          <PurchaseCoins
            price_id="price_1PfJ44P8KW8pdlk1qEkHZkmJ"
            price="23.99"
            coins="1350"
            image="/coins_3.png"
            email={email}
          />
          <PurchaseCoins
            price_id="price_1PfJ4NP8KW8pdlk1MBVoEEUf"
            price="47.99"
            coins="2800"
            image="/coins_4.png"  
            email={email}
          />
          <PurchaseCoins
            price_id="price_1PfJ4iP8KW8pdlk1qBgPRSqo"
            price="119.99"
            coins="7750"
            image="/coins_5.png"  
            email={email}
          />
        </div>
      </DialogContent>
    </Dialog>)
  );
}
